config/routes.rb
RedditClone::Application.routes.draw do
  resources :linkpost
  devise_for :users
  

end

app/models/linkpost.rb
class Linkpost < ActiveRecord::Base
	belongs_to :user
	validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :linkposts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/linkposts_controller.rb
class LinkpostsController < ApplicationController
  before_action :set_linkpost, only: [:show, :edit, :update, :destroy]

  # GET /linkposts
  # GET /linkposts.json
  def index
    @linkposts = Linkpost.all
  end

  # GET /linkposts/1
  # GET /linkposts/1.json
  def show
  end

  # GET /linkposts/new
  def new
    @linkpost = Linkpost.new
  end

  # GET /linkposts/1/edit
  def edit
  end

  # POST /linkposts
  # POST /linkposts.json
  def create
    @linkpost = Linkpost.new(linkpost_params)

    respond_to do |format|
      if @linkpost.save
        format.html { redirect_to @linkpost, notice: 'Linkpost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @linkpost }
      else
        format.html { render action: 'new' }
        format.json { render json: @linkpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linkposts/1
  # PATCH/PUT /linkposts/1.json
  def update
    respond_to do |format|
      if @linkpost.update(linkpost_params)
        format.html { redirect_to @linkpost, notice: 'Linkpost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @linkpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkposts/1
  # DELETE /linkposts/1.json
  def destroy
    @linkpost.destroy
    respond_to do |format|
      format.html { redirect_to linkposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linkpost
      @linkpost = Linkpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linkpost_params
      params.require(:linkpost).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linkposts_helper.rb
module LinkpostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/linkposts/_form.html.erb
<%= form_for(@linkpost) do |f| %>
  <% if @linkpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linkpost.errors.count, "error") %> prohibited this linkpost from being saved:</h2>

      <ul>
      <% @linkpost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linkposts/edit.html.erb
<h1>Editing linkpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @linkpost %> |
<%= link_to 'Back', linkposts_path %>

app/views/linkposts/index.html.erb
<h1>Listing linkposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @linkposts.each do |linkpost| %>
      <tr>
        <td><%= linkpost.title %></td>
        <td><%= linkpost.user_id %></td>
        <td><%= link_to 'Show', linkpost %></td>
        <td><%= link_to 'Edit', edit_linkpost_path(linkpost) %></td>
        <td><%= link_to 'Destroy', linkpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linkpost', new_linkpost_path %>

app/views/linkposts/new.html.erb
<h1>New linkpost</h1>

<%= render 'form' %>

<%= link_to 'Back', linkposts_path %>

app/views/linkposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @linkpost.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @linkpost.user_id %>
</p>

<%= link_to 'Edit', edit_linkpost_path(@linkpost) %> |
<%= link_to 'Back', linkposts_path %>